#!/bin/bash

DEFAULT_VERSION=v0.0.0

if [ -d .git ] ; then
	VERSION=$(git describe --always --dirty 2>/dev/null)
fi

if [ -z "$VERSION" ] ; then
	VERSION=$DEFAULT_VERSION
fi

if [ ! -f src/version.hh ] || ! grep -q \"$VERSION\" src/version.hh ; then
	echo "#define ROSA_VERSION \"$VERSION\"" > src/version.hh
fi

cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ .
make
