#!/bin/bash

DEFAULT_VERSION=v0.0.0

if [ -d .git ] ; then
	VERSION=$(git describe --dirty 2>/dev/null)
fi

if [ -z "$VERSION" ] ; then
	VERSION=$DEFAULT_VERSION
fi

if [ ! -f src/version.hh ] || ! grep -q \"$VERSION\" src/version.hh ; then
	echo "#define SPOONY_VERSION \"$VERSION\"" > src/version.hh
fi

tup
