#!/bin/bash

ROUTE=$1
MAXSTEP=$2
TARGET=$3
MIN=${4:-0}
MAX=${5:-255}
ARGS=${@:6:99}

mkdir -p $TARGET && echo "Created target directory"

for i in $(seq -f %03.0f $MIN $MAX) ; do
	filename=$TARGET/$i.txt
	seed=$(expr $i + 0)

	echo -n "[$(date +'%Y-%m-%d %H:%M:%S')] Generating seed $seed..."
	src/rosa -r $ROUTE -s $seed -m $MAXSTEP $ARGS > $filename 2>/dev/null
	echo " done!"
done
