#!/bin/bash

tools/generate-route premist > data/routes/premist.txt
tools/generate-route paladin > data/routes/paladin.txt
tools/generate-route yes64 > data/routes/yes64.txt
tools/generate-route no64-drain > data/routes/no64-drain.txt
tools/generate-route no64-excalbur > data/routes/no64-excalbur.txt
tools/generate-route no64-rosa > data/routes/no64-rosa.txt
tools/generate-route no64-drain-to-giant > data/routes/no64-drain-to-giant.txt
tools/generate-route no64-excalbur-to-giant > data/routes/no64-excalbur-to-giant.txt
tools/generate-route post-giant > data/routes/post-giant.txt
tools/generate-route ss-drain > data/routes/ss-drain.txt
tools/generate-route ss-excalbur > data/routes/ss-excalbur.txt
tools/generate-route marathon-no64-drain > data/routes/marathon-no64-drain.txt
tools/generate-route marathon-no64-excalbur > data/routes/marathon-no64-excalbur.txt
tools/generate-route marathon-no64-excalbur-bosses > data/routes/marathon-no64-excalbur-bosses.txt
tools/generate-route tas-rosa > data/routes/tas-rosa.txt
tools/generate-route tas-drain > data/routes/tas-drain.txt
tools/generate-route tas-excalbur > data/routes/tas-excalbur.txt
